"""add_auth_and_recovery_fields_to_usuario

Revision ID: 0c6bf197c769
Revises: 1688f0d529c4
Create Date: 2026-09-03 09:09:55.760855

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c6bf197c769'
down_revision: Union[str, None] = '1688f0d529c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('pin_seguranca_hash', sa.String(length=255), nullable=True))
    op.add_column('usuario', sa.Column('codigo_ativacao', sa.String(length=50), nullable=True))
    op.add_column('usuario', sa.Column('codigo_liberacao_master', sa.String(length=50), nullable=True))
    op.add_column('usuario', sa.Column('liberacao_expira_em', sa.DateTime(timezone=True), nullable=True))
    op.add_column('usuario', sa.Column('status_conta', sa.String(length=30), nullable=False))
    op.alter_column('usuario', 'email',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)
    op.create_index(op.f('ix_usuario_status_conta'), 'usuario', ['status_conta'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usuario_status_conta'), table_name='usuario')
    op.alter_column('usuario', 'email',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
    op.drop_column('usuario', 'status_conta')
    op.drop_column('usuario', 'liberacao_expira_em')
    op.drop_column('usuario', 'codigo_liberacao_master')
    op.drop_column('usuario', 'codigo_ativacao')
    op.drop_column('usuario', 'pin_seguranca_hash')
    # ### end Alembic commands ###
