"""initial_models_v2

Revision ID: 1688f0d529c4
Revises: 
Create Date: 2026-09-02 20:01:17.893931

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1688f0d529c4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('modulo_assinatura',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_modulo_assinatura_codigo'), 'modulo_assinatura', ['codigo'], unique=True)
    op.create_table('organizacao',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('razao_social', sa.String(length=150), nullable=False),
    sa.Column('nome_fantasia', sa.String(length=150), nullable=False),
    sa.Column('cnpj', sa.String(length=14), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizacao_cnpj'), 'organizacao', ['cnpj'], unique=True)
    op.create_table('produto',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('codigo_anp', sa.String(length=20), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('categoria', sa.Enum('GASOLINA', 'ETANOL', 'DIESEL', 'BIODIESEL', name='categoriaproduto', native_enum=False), nullable=False),
    sa.Column('unidade_medida', sa.String(length=10), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_produto_codigo_anp'), 'produto', ['codigo_anp'], unique=True)
    op.create_table('usuario',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('sobrenome', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('cpf', sa.String(length=11), nullable=False),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('cargo', sa.String(length=100), nullable=True),
    sa.Column('registro_profissional', sa.String(length=50), nullable=True),
    sa.Column('senha_hash', sa.String(length=255), nullable=False),
    sa.Column('tipo_usuario', sa.Enum('ADMIN_SISTEMA', 'USUARIO_TERMINAL', 'CLIENTE_CONGENERE', name='tipousuario', native_enum=False), nullable=False),
    sa.Column('is_master', sa.Boolean(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuario_cpf'), 'usuario', ['cpf'], unique=True)
    op.create_index(op.f('ix_usuario_email'), 'usuario', ['email'], unique=True)
    op.create_table('modulo_funcionalidade',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('modulo_id', sa.BigInteger(), nullable=False),
    sa.Column('chave', sa.String(length=100), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('tipo_acao', sa.Enum('VISUALIZAR', 'CRIAR', 'EDITAR', 'APROVAR', 'EXCLUIR', name='tipoacaofuncionalidade', native_enum=False), nullable=False),
    sa.ForeignKeyConstraint(['modulo_id'], ['modulo_assinatura.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_modulo_funcionalidade_chave'), 'modulo_funcionalidade', ['chave'], unique=True)
    op.create_table('terminal',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('organizacao_id', sa.BigInteger(), nullable=False),
    sa.Column('codigo_terminal', sa.String(length=50), nullable=False),
    sa.Column('razao_social', sa.String(length=150), nullable=False),
    sa.Column('nome_fantasia', sa.String(length=150), nullable=False),
    sa.Column('cnpj', sa.String(length=14), nullable=False),
    sa.Column('inscricao_estadual', sa.String(length=30), nullable=False),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('telefone_financeiro', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('email_financeiro', sa.String(length=100), nullable=True),
    sa.Column('cep', sa.String(length=8), nullable=True),
    sa.Column('logradouro', sa.String(length=150), nullable=True),
    sa.Column('numero', sa.String(length=20), nullable=True),
    sa.Column('complemento', sa.String(length=100), nullable=True),
    sa.Column('bairro', sa.String(length=100), nullable=True),
    sa.Column('cidade', sa.String(length=100), nullable=True),
    sa.Column('uf', sa.String(length=2), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organizacao_id'], ['organizacao.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organizacao_id', 'codigo_terminal', name='uq_terminal_org_codigo')
    )
    op.create_index(op.f('ix_terminal_codigo_terminal'), 'terminal', ['codigo_terminal'], unique=False)
    op.create_table('auditoria_log',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('terminal_id', sa.BigInteger(), nullable=True),
    sa.Column('tabela_nome', sa.String(length=60), nullable=False),
    sa.Column('registro_id', sa.BigInteger(), nullable=False),
    sa.Column('acao', sa.Enum('INSERT', 'UPDATE', 'DELETE', name='acaoauditoria', native_enum=False), nullable=False),
    sa.Column('dados_anteriores', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('dados_novos', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('motivo', sa.Text(), nullable=True),
    sa.Column('usuario_id', sa.BigInteger(), nullable=True),
    sa.Column('ip_origem', sa.String(length=45), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['terminal_id'], ['terminal.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_auditoria_tabela_reg', 'auditoria_log', ['tabela_nome', 'registro_id', 'criado_em'], unique=False)
    op.create_index(op.f('ix_auditoria_log_criado_em'), 'auditoria_log', ['criado_em'], unique=False)
    op.create_index(op.f('ix_auditoria_log_registro_id'), 'auditoria_log', ['registro_id'], unique=False)
    op.create_index(op.f('ix_auditoria_log_tabela_nome'), 'auditoria_log', ['tabela_nome'], unique=False)
    op.create_index(op.f('ix_auditoria_log_terminal_id'), 'auditoria_log', ['terminal_id'], unique=False)
    op.create_table('congenere',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('terminal_id', sa.BigInteger(), nullable=False),
    sa.Column('razao_social', sa.String(length=150), nullable=False),
    sa.Column('cnpj', sa.String(length=14), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['terminal_id'], ['terminal.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('laboratorio',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('terminal_id', sa.BigInteger(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['terminal_id'], ['terminal.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plataforma',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('terminal_id', sa.BigInteger(), nullable=False),
    sa.Column('identificador', sa.String(length=50), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=True),
    sa.Column('tipo', sa.Enum('DESCARGA', 'CARREGAMENTO', 'MISTA', name='tipoplataforma', native_enum=False), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['terminal_id'], ['terminal.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tanque',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('terminal_id', sa.BigInteger(), nullable=False),
    sa.Column('produto_id', sa.BigInteger(), nullable=False),
    sa.Column('identificador_tanque', sa.String(length=50), nullable=False),
    sa.Column('capacidade_nominal_litros', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('capacidade_operacional_litros', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('volume_atual_litros', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['produto_id'], ['produto.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['terminal_id'], ['terminal.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('terminal_modulo_contratado',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('terminal_id', sa.BigInteger(), nullable=False),
    sa.Column('modulo_id', sa.BigInteger(), nullable=False),
    sa.Column('data_inicio', sa.Date(), nullable=False),
    sa.Column('data_fim', sa.Date(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['modulo_id'], ['modulo_assinatura.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['terminal_id'], ['terminal.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('terminal_id', 'modulo_id', name='uq_terminal_modulo')
    )
    op.create_table('terminal_produto',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('terminal_id', sa.BigInteger(), nullable=False),
    sa.Column('produto_id', sa.BigInteger(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['produto_id'], ['produto.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['terminal_id'], ['terminal.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('terminal_id', 'produto_id', name='uq_terminal_produto')
    )
    op.create_table('usuario_terminal',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('usuario_id', sa.BigInteger(), nullable=False),
    sa.Column('terminal_id', sa.BigInteger(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['terminal_id'], ['terminal.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id', 'terminal_id', name='uq_usuario_terminal')
    )
    op.create_table('bico',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('terminal_id', sa.BigInteger(), nullable=False),
    sa.Column('plataforma_id', sa.BigInteger(), nullable=False),
    sa.Column('produto_id', sa.BigInteger(), nullable=False),
    sa.Column('identificador_bico', sa.String(length=50), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['plataforma_id'], ['plataforma.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['produto_id'], ['produto.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['terminal_id'], ['terminal.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('operacao_veiculo',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('terminal_id', sa.BigInteger(), nullable=False),
    sa.Column('congenere_id', sa.BigInteger(), nullable=False),
    sa.Column('nome_transportadora', sa.String(length=150), nullable=False),
    sa.Column('is_transportadora_propria', sa.Boolean(), nullable=False),
    sa.Column('placa_veiculo', sa.String(length=10), nullable=False),
    sa.Column('nome_motorista', sa.String(length=150), nullable=False),
    sa.Column('numero_nota_fiscal', sa.String(length=50), nullable=False),
    sa.Column('origem_destino', sa.String(length=150), nullable=False),
    sa.Column('tipo_operacao', sa.Enum('DESCARGA', 'CARREGAMENTO', name='tipooperacao', native_enum=False), nullable=False),
    sa.Column('status_operacao', sa.Enum('AGUARDANDO_PORTARIA', 'EM_AMOSTRAGEM', 'EM_ANALISE_LAB', 'APROVADO_OPERACAO', 'EM_OPERACAO', 'CONCLUIDO', 'REPROVADO', 'CANCELADO', name='statusoperacao', native_enum=False), nullable=False),
    sa.Column('data_hora_entrada', sa.DateTime(timezone=True), nullable=False),
    sa.Column('data_hora_saida', sa.DateTime(timezone=True), nullable=True),
    sa.Column('observacao_geral', sa.Text(), nullable=True),
    sa.Column('motivo_cancelamento', sa.Text(), nullable=True),
    sa.Column('usuario_registro_id', sa.BigInteger(), nullable=False),
    sa.Column('usuario_liberacao_saida_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['congenere_id'], ['congenere.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['terminal_id'], ['terminal.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['usuario_liberacao_saida_id'], ['usuario.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['usuario_registro_id'], ['usuario.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_operacao_terminal_data', 'operacao_veiculo', ['terminal_id', 'data_hora_entrada'], unique=False)
    op.create_index(op.f('ix_operacao_veiculo_numero_nota_fiscal'), 'operacao_veiculo', ['numero_nota_fiscal'], unique=False)
    op.create_index(op.f('ix_operacao_veiculo_placa_veiculo'), 'operacao_veiculo', ['placa_veiculo'], unique=False)
    op.create_index(op.f('ix_operacao_veiculo_terminal_id'), 'operacao_veiculo', ['terminal_id'], unique=False)
    op.create_table('usuario_permissao',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('usuario_terminal_id', sa.BigInteger(), nullable=False),
    sa.Column('funcionalidade_id', sa.BigInteger(), nullable=False),
    sa.Column('permitido', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['funcionalidade_id'], ['modulo_funcionalidade.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_terminal_id'], ['usuario_terminal.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_terminal_id', 'funcionalidade_id', name='uq_usuario_funcionalidade')
    )
    op.create_table('bico_tanque_vinculo',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('bico_id', sa.BigInteger(), nullable=False),
    sa.Column('tanque_id', sa.BigInteger(), nullable=False),
    sa.Column('is_padrao', sa.Boolean(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['bico_id'], ['bico.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tanque_id'], ['tanque.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bico_id', 'tanque_id', name='uq_bico_tanque')
    )
    op.create_table('operacao_compartimento',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('operacao_id', sa.BigInteger(), nullable=False),
    sa.Column('numero_compartimento', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.BigInteger(), nullable=False),
    sa.Column('volume_nf_litros', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('capacidade_compartimento_litros', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['operacao_id'], ['operacao_veiculo.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['produto_id'], ['produto.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('operacao_id', 'numero_compartimento', name='uq_operacao_num_compartimento')
    )
    op.create_table('operacao_status_historico',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('operacao_id', sa.BigInteger(), nullable=False),
    sa.Column('status_anterior', sa.String(length=30), nullable=True),
    sa.Column('status_novo', sa.String(length=30), nullable=False),
    sa.Column('data_hora', sa.DateTime(timezone=True), nullable=False),
    sa.Column('usuario_id', sa.BigInteger(), nullable=False),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['operacao_id'], ['operacao_veiculo.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('amostra',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('operacao_id', sa.BigInteger(), nullable=False),
    sa.Column('compartimento_id', sa.BigInteger(), nullable=False),
    sa.Column('produto_id', sa.BigInteger(), nullable=False),
    sa.Column('codigo_amostra', sa.String(length=50), nullable=False),
    sa.Column('temperatura_coleta_celsius', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('tipo_coleta', sa.Enum('CORRIDO', 'TOPO', 'MEIO', 'FUNDO', name='tipocoleta', native_enum=False), nullable=False),
    sa.Column('is_recoleta', sa.Boolean(), nullable=False),
    sa.Column('has_descarga', sa.Boolean(), nullable=True),
    sa.Column('amostra_origem_recoleta_id', sa.BigInteger(), nullable=True),
    sa.Column('tanque_descarga_pretendido_id', sa.BigInteger(), nullable=True),
    sa.Column('status_amostra', sa.Enum('AGUARDANDO_ANALISE', 'EM_ANALISE', 'APROVADA', 'REPROVADA', 'RECOLETA_SOLICITADA', name='statusamostra', native_enum=False), nullable=False),
    sa.Column('data_hora_coleta', sa.DateTime(timezone=True), nullable=False),
    sa.Column('operador_id', sa.BigInteger(), nullable=False),
    sa.Column('motivo_reprovacao', sa.Text(), nullable=True),
    sa.Column('motivo_recoleta', sa.Text(), nullable=True),
    sa.Column('origemMp', sa.Enum('VEGETAL', 'ANIMAL', name='origemmp', native_enum=False), nullable=False),
    sa.ForeignKeyConstraint(['amostra_origem_recoleta_id'], ['amostra.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['compartimento_id'], ['operacao_compartimento.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['operacao_id'], ['operacao_veiculo.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['operador_id'], ['usuario.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['produto_id'], ['produto.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tanque_descarga_pretendido_id'], ['tanque.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_amostra_codigo_amostra'), 'amostra', ['codigo_amostra'], unique=True)
    op.create_index(op.f('ix_amostra_operacao_id'), 'amostra', ['operacao_id'], unique=False)
    op.create_table('analise_amostra',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('amostra_id', sa.BigInteger(), nullable=False),
    sa.Column('analista_id', sa.BigInteger(), nullable=False),
    sa.Column('laboratorio_id', sa.BigInteger(), nullable=False),
    sa.Column('data_hora_inicio', sa.DateTime(timezone=True), nullable=False),
    sa.Column('data_hora_fim', sa.DateTime(timezone=True), nullable=True),
    sa.Column('parecer_final', sa.Enum('EM_ANDAMENTO', 'CONFORME', 'NAO_CONFORME', 'RECOLETA', name='parecerlaudo', native_enum=False), nullable=False),
    sa.Column('visto_analista', sa.String(length=100), nullable=True),
    sa.Column('data_hora_visto', sa.DateTime(timezone=True), nullable=True),
    sa.Column('visto_registro_snapshot', sa.String(length=150), nullable=True),
    sa.Column('hash_integridade_visto', sa.String(length=64), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('densidade_kg_l', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('temperatura_ensaio_celsius', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('fator_correcao', sa.Numeric(precision=7, scale=5), nullable=True),
    sa.Column('massa_especifica_20c_kg_l', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('grau_inpm', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('teor_etanol_gasolina_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('teor_agua_ppm', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('aspecto', sa.String(length=50), nullable=True),
    sa.Column('cor', sa.String(length=50), nullable=True),
    sa.Column('material_particulado', sa.Boolean(), nullable=True),
    sa.Column('agua_livre', sa.Boolean(), nullable=True),
    sa.Column('ponto_fulgor_celsius', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('condutividade_eletrica', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('metanol', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('destilacao', sa.Boolean(), nullable=True),
    sa.Column('resultados_extras', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['amostra_id'], ['amostra.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['analista_id'], ['usuario.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['laboratorio_id'], ['laboratorio.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('amostra_id')
    )
    op.create_table('comprovante_operacao',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('operacao_id', sa.BigInteger(), nullable=False),
    sa.Column('produto_id', sa.BigInteger(), nullable=False),
    sa.Column('amostra_representativa_id', sa.BigInteger(), nullable=False),
    sa.Column('congenere_id', sa.BigInteger(), nullable=False),
    sa.Column('numero_sicof', sa.String(length=50), nullable=False),
    sa.Column('lancamento_sicof', sa.String(length=50), nullable=True),
    sa.Column('numero_nota_fiscal', sa.String(length=50), nullable=False),
    sa.Column('data_geracao', sa.Date(), nullable=False),
    sa.Column('hora_geracao', sa.Time(), nullable=False),
    sa.Column('densidade_20c_apurada', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('fator_correcao_fcv', sa.Numeric(precision=7, scale=5), nullable=False),
    sa.Column('grau_inpm', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('volume_ambiente_nf_litros', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('volume_20c_nf_litros', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('volume_ambiente_apurado_litros', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('volume_20c_litros', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('resultado_variacao_litros', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('retirada_litros', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('complemento_litros', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDENTE', 'DISPONIVEL', 'CANCELADO', name='statuscomprovante', native_enum=False), nullable=False),
    sa.Column('criado_por_usuario_id', sa.BigInteger(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['amostra_representativa_id'], ['amostra.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['congenere_id'], ['congenere.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['criado_por_usuario_id'], ['usuario.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['operacao_id'], ['operacao_veiculo.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['produto_id'], ['produto.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comprovante_operacao_numero_sicof'), 'comprovante_operacao', ['numero_sicof'], unique=False)
    op.create_index(op.f('ix_comprovante_operacao_operacao_id'), 'comprovante_operacao', ['operacao_id'], unique=False)
    op.create_table('comprovante_tanque_alocacao',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('comprovante_id', sa.BigInteger(), nullable=False),
    sa.Column('tanque_id', sa.BigInteger(), nullable=False),
    sa.Column('bico_id', sa.BigInteger(), nullable=False),
    sa.Column('volume_alocado_litros', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['bico_id'], ['bico.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['comprovante_id'], ['comprovante_operacao.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tanque_id'], ['tanque.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comprovante_tanque_alocacao')
    op.drop_index(op.f('ix_comprovante_operacao_operacao_id'), table_name='comprovante_operacao')
    op.drop_index(op.f('ix_comprovante_operacao_numero_sicof'), table_name='comprovante_operacao')
    op.drop_table('comprovante_operacao')
    op.drop_table('analise_amostra')
    op.drop_index(op.f('ix_amostra_operacao_id'), table_name='amostra')
    op.drop_index(op.f('ix_amostra_codigo_amostra'), table_name='amostra')
    op.drop_table('amostra')
    op.drop_table('operacao_status_historico')
    op.drop_table('operacao_compartimento')
    op.drop_table('bico_tanque_vinculo')
    op.drop_table('usuario_permissao')
    op.drop_index(op.f('ix_operacao_veiculo_terminal_id'), table_name='operacao_veiculo')
    op.drop_index(op.f('ix_operacao_veiculo_placa_veiculo'), table_name='operacao_veiculo')
    op.drop_index(op.f('ix_operacao_veiculo_numero_nota_fiscal'), table_name='operacao_veiculo')
    op.drop_index('idx_operacao_terminal_data', table_name='operacao_veiculo')
    op.drop_table('operacao_veiculo')
    op.drop_table('bico')
    op.drop_table('usuario_terminal')
    op.drop_table('terminal_produto')
    op.drop_table('terminal_modulo_contratado')
    op.drop_table('tanque')
    op.drop_table('plataforma')
    op.drop_table('laboratorio')
    op.drop_table('congenere')
    op.drop_index(op.f('ix_auditoria_log_terminal_id'), table_name='auditoria_log')
    op.drop_index(op.f('ix_auditoria_log_tabela_nome'), table_name='auditoria_log')
    op.drop_index(op.f('ix_auditoria_log_registro_id'), table_name='auditoria_log')
    op.drop_index(op.f('ix_auditoria_log_criado_em'), table_name='auditoria_log')
    op.drop_index('idx_auditoria_tabela_reg', table_name='auditoria_log')
    op.drop_table('auditoria_log')
    op.drop_index(op.f('ix_terminal_codigo_terminal'), table_name='terminal')
    op.drop_table('terminal')
    op.drop_index(op.f('ix_modulo_funcionalidade_chave'), table_name='modulo_funcionalidade')
    op.drop_table('modulo_funcionalidade')
    op.drop_index(op.f('ix_usuario_email'), table_name='usuario')
    op.drop_index(op.f('ix_usuario_cpf'), table_name='usuario')
    op.drop_table('usuario')
    op.drop_index(op.f('ix_produto_codigo_anp'), table_name='produto')
    op.drop_table('produto')
    op.drop_index(op.f('ix_organizacao_cnpj'), table_name='organizacao')
    op.drop_table('organizacao')
    op.drop_index(op.f('ix_modulo_assinatura_codigo'), table_name='modulo_assinatura')
    op.drop_table('modulo_assinatura')
    # ### end Alembic commands ###
