"""align_usuario_papel_and_terminal_scopes

Revision ID: 88f3fba3a43c
Revises: ac69e4869fb4
Create Date: 2026-09-03 11:43:18.877363

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88f3fba3a43c'
down_revision: Union[str, None] = 'ac69e4869fb4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('papel', sa.Enum('PORTEIRO', 'QUIMICO', 'OPERADOR', 'ADM', 'CONGENERE', name='papelusuario', native_enum=False), nullable=True))
    op.drop_column('usuario', 'registro_profissional')
    op.drop_column('usuario', 'cargo')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('cargo', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('usuario', sa.Column('registro_profissional', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_column('usuario', 'papel')
    # ### end Alembic commands ###
