"""create_convite_cadastro_table

Revision ID: ac69e4869fb4
Revises: 0c6bf197c769
Create Date: 2026-09-03 09:37:45.963670

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac69e4869fb4'
down_revision: Union[str, None] = '0c6bf197c769'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('convite_cadastro',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('utilizado', sa.Boolean(), nullable=False),
    sa.Column('utilizado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('organizacao_id', sa.BigInteger(), nullable=True),
    sa.Column('expira_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organizacao_id'], ['organizacao.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organizacao_id')
    )
    op.create_index(op.f('ix_convite_cadastro_codigo'), 'convite_cadastro', ['codigo'], unique=True)
    op.create_index(op.f('ix_convite_cadastro_utilizado'), 'convite_cadastro', ['utilizado'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_convite_cadastro_utilizado'), table_name='convite_cadastro')
    op.drop_index(op.f('ix_convite_cadastro_codigo'), table_name='convite_cadastro')
    op.drop_table('convite_cadastro')
    # ### end Alembic commands ###
